IOP_BIN = ../ps2ip.irx
IOP_CFLAGS += -mno-check-zero-division
IOP_OBJS = main.o smap.o xfer.o ministack_eth.o ministack_arp.o ministack_ip.o ministack_udp.o udptty.o exports.o imports.o

include ../global.make
